secrets:
  mariadb_root_password:
    file: ../.secrets/mariadb/mariadb_root_password.txt
  mariadb_user_password:
    file: ../.secrets/mariadb/mariadb_user_password.txt
  wordpress_root_password:
    file: ../.secrets/wordpress/wordpress_root_password.txt
  wordpress_user_password:
    file: ../.secrets/wordpress/wordpress_user_password.txt

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    env_file:
      .env
    depends_on:
      - wordpress
    ports:
      - "0.0.0.0:443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      .env
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - mariadb_root_password
      - mariadb_user_password
    networks:
      - inception_network
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      .env
    environment:
      - WP_REDIS_HOST=redis
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - mariadb_root_password
      - mariadb_user_password
      - wordpress_root_password
      - wordpress_user_password
    networks:
      - inception_network
    restart: always

  redis:
    build:
      context: ./bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    networks:
      - inception_network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  ftp:
    build:
      context: ./bonus/ftp
      dockerfile: Dockerfile
    container_name: ftp
    networks:
      - inception_network
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ftp_data:/home/ftpuser/ftp
    restart: unless-stopped

  adminer:
    build:
      context: ./bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer
    networks:
      - inception_network
    restart: unless-stopped


volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  ftp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/ftp
  redis_data:
    driver: local

networks:
  inception_network:
    driver: bridge
